// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Build.Framework;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using RequiredAttribute = System.ComponentModel.DataAnnotations.RequiredAttribute;

namespace Animal_Rescue.Models
{
    public partial class AnimalRescue
    {
        public int ID { get; set; }
        [DisplayName("ID")]
        public string PrefixedID { get; set; }
        public string Species { get; set; }
        public string Name { get; set; }
        [StringLength(1)]
        public string Gender { get; set; }
        public string Spayed { get; set; }
        public string Breed { get; set; }
        public string Colour { get; set; }
        [DataType(DataType.DateTime)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [Required]
        public DateTime? Birthday { get; set; }
        public string Vaccine_Status { get; set; }
        public string Identification { get; set; }
        public int? IdentificationNumber { get; set; }
        public int? Adoption_fee { get; set; }
    }
}